stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_dataingestion_01.py
    deps:
      - src/cnnClassifier/pipeline/stage_dataingestion_01.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset_mlops


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_base_model_prepare_02.py
    deps:
      - src/cnnClassifier/pipeline/stage_base_model_prepare_02.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage_model_train_03.py
    deps:
      - src/cnnClassifier/pipeline/stage_model_train_03.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_mlops
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/trained_model/


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_evaluation_04.py
    deps:
      - src/cnnClassifier/pipeline/stage_evaluation_04.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_mlops
      - artifacts/trained_model/
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    outs:
      - evaluation/scores.json


        

